name: Bug Report
description: File a bug report
title: "M00-LAB00: QUICK_DESCRIPTION"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this bug report!
        
        **Replace issue name LAB00:QUICK_DESCRIPTION, for example "LAB01: My new issue"**
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info 😉?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened?
      placeholder: Tell us what you see!
      value: |
        Exercise : 00
        Task: 00
        Step: 00
        
        Description of issue:

        Repro steps:
        1.
        1.
        1.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Lab
      description: Lab name
      options:
        - Other
        - Lab 00 Validate lab environment
        - Lab 01 Agile planning and portfolio management with Azure Boards
        - Lab 02 Version controlling with Git in Azure Repos
        - Lab 03 Configuring agent pools and understanding pipeline styles
        - Lab 04 Enabling continuous integration with Azure Pipelines
        - Lab 05 Implementing GitHub Actions by using DevOps Starter
        - Lab 06 Deploying Docker Containers to Azure App Service web apps
        - Lab 07 Control Deployments using Release Gates
        - Lab 08 Configuring pipelines as code with YAML
        - Lab 09 Setting up and running functional tests
        - Lab 10 Integrate Azure Key Vault with Azure DevOps
        - Lab 11 Enable Dynamic Configuration and Feature Flags
        - Lab 12 Deployments using Azure Bicep templates
        - Lab 13 Implement security and compliance in Azure DevOps Pipelines
        - Lab 14 Managing technical debt with SonarQube and Azure DevOps
        - Lab 15 Package management with Azure Artifacts
        - Lab 16 Monitoring application performance with Application Insights
        - Lab 17 Sharing Team Knowledge using Azure Project Wikis
    validations:
      required: true
  - type: textarea
    id: Screenshots
    attributes:
      label: Relevant screenshots
      description: Please copy and paste any relevant screenshots 📸
      value: paste here 😉 
  - type: checkboxes
    id: terms
    attributes:
      label: Do you want to help us? 👏
      description: GitHub/Git uses Pull Requests (PR) to propose and collaborate on changes to a repository. **No git/github experience?** Follow the [video in the Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#easy-prs-using-github-no-gitgithub-knowledge-needed)
      options:
        - label: Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)
          required: false
